import Head from "next/head";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "@/components/BlogCard";
import Footer from "@/components/Footer";

const graphcms = new GraphQLClient(
  "https://api-eu-west-2.hygraph.com/v2/clg9b9s6x25mw01t3fdf1bepc/master"
);

const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  return (
    <div className="">
      <Head>
        <title>News App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-10 md:flex-wrap-reverse md:w-full md:pl-[20px] md:pr-[20px] space-y-10 md:flex md:flex-row md:justify-center md:space-x-6 flex flex-col-reverse  items-center  md:space-y-10 md:mt-0">
        {posts.map((post) => (
          <BlogCard
            title={post.title}
            author={post.author}
            coverPhoto={post.coverPhoto}
            key={post.id}
            datePublished={post.datePublished}
            slug={post.slug}
          />
        ))}
      </div>
      <Footer />
    </div>
  );
}
